
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Phanindra V.V.D
 */
public class T_ScrollPane_GUI extends javax.swing.JPanel implements Runnable {

    /**
     * Creates new form T_ScrollPane_GUI
     */
    protected String hostID[] = new String[100];
    protected String hostNames[] = new String[100];
    private int n, i; //No.of Connections
    private DefaultListModel dlm;
    protected Teacher_GUI tgGUI;
    protected T_Chat_GUI chtGUI[];
    private T_DataTransfer DT;
    private String ID, name;
    protected int index; 
    
    public T_ScrollPane_GUI(Teacher_GUI obj) {
        initComponents();
        
        tgGUI = obj;
        dlm = (DefaultListModel)jList1.getModel();
        n = 0;
        chtGUI = new T_Chat_GUI[100];
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setLayout(new java.awt.CardLayout());

        listPanel.setLayout(new java.awt.CardLayout());

        jList1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jList1.setModel(new javax.swing.DefaultListModel());
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        listPanel.add(jScrollPane1, "card2");

        add(listPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        // TODO add your handling code here:
        try{
            int i = getIndex();
            index = i;
            updatePanel(i);
        }
        catch(Exception e)
        {
            System.out.println("Exception !! "+e);
        }
        
        
    }//GEN-LAST:event_jList1MousePressed

    @Override
    public void run() {
   
        receiveIDS();
        DT = new T_DataTransfer(this);
        new Thread(DT).start();
    }
    
    private void initialize()
    {
        try {
            ID = (String)tgGUI.input.readUTF();
            name = (String)tgGUI.input.readUTF();
            update(ID, name);
        } catch (IOException ex) {
            System.out.println("IOException : "+ex);
        }
    }
    
    protected int getIDIndex(String ID)
    {
        for(i=0; i<n; i++)
        {
            if(ID.equals(hostID[i]))
            {
                break;
            }
        }
        return i;
    }
    
    protected void remove(String ID)
    {
        i = getIDIndex(ID);
        
        dlm.remove(i);
        JOptionPane.showMessageDialog(this, hostNames[i]+" got disconnected");
        
        for(;i<n-1; i++)
        {
            hostID[i] = hostID[i+1];
            hostNames[i] = hostNames[i+1];
            chtGUI[i] = chtGUI[i+1];
        }
        n--;
    }
     
    
    private void receiveIDS()
    {
        try {
            int n, i=0;
            String s;
            
            //Receive No. of host connections
            s = tgGUI.input.readUTF();
            n = Integer.parseInt(s);
            
            if(n==0)
                initialize();
            
            while(i<n)
            {
                ID = (String)tgGUI.input.readUTF();
                name = (String)tgGUI.input.readUTF();
                update(ID, name);               
                i++;
            }
            
            
        } catch (IOException ex) {
            System.out.println("IOException : "+ex);
        }
    }
    
    protected void update(String msg, String name)
    {
        dlm.addElement(name);
        hostNames[n] = name;
        hostID[n] = msg;
        create(n);
        n++;
    }
    
    protected void create(int i)
    {
        chtGUI[i] = new T_Chat_GUI(this, i);
    }
    
    protected void updatePanel(int i)
    {
        tgGUI.jPanel2.removeAll();
        tgGUI.jPanel2.repaint();
        tgGUI.jPanel2.revalidate();
        
        tgGUI.jPanel2.add(chtGUI[i].chatPanel);
        tgGUI.jPanel2.repaint();
        tgGUI.jPanel2.revalidate();
    }

    protected int getIndex()
    {
        return(jList1.getSelectedIndex());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JList jList1;
    protected javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JPanel listPanel;
    // End of variables declaration//GEN-END:variables

}
